openapi: 3.0.3
info:
  version: 1.0.0
  title: Twitter API
  description: >-
    This is a sample server Twitter API server.

servers:
  - url: http://localhost:9000
    description: Development server
  - url: https://ecs-alb-1730402.ap-northeast-1.elb.amazonaws.com/
    description: Production server

paths:
  /:
    get:
      summary: Root API
      description: Return root message
      responses:
        "200":
          description: A successful response
          content:
            text/plain:
              schema:
                type: string
                example: It works
  /hello:
    get:
      summary: Hello API
      description: Return Hello message
      parameters:
        - name: lang
          in: query
          description: Language selection
          required: false
          schema:
            type: string
            enum:
              - ja
              - en
            default: ja
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: こんにちは 世界
        "400":
          description: Invalid language
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid language parameter
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error404Response"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Response"
  /tweets:
    get:
      summary: Get tweets
      description: Return tweets
      parameters:
        - name: limit
          in: query
          description: Limit
          required: false
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          description: Offset
          required: false
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TweetsList"
        "400":
          description: Invalid parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid parameter
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error404Response"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Response"
    post:
      summary: Post tweet
      description: Return id and created time
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "Reference to User ID"
                  example: 1
                title:
                  type: string
                  example: Hello World
                body:
                  type: string
                  example: Hello World
              required:
                - user_id
                - title
                - body
      responses:
        "201":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  created_at:
                    type: string
                    format: date-time
                    example: 2021-01-01T00:00:00Z
        "400":
          description: Invalid requestBody
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid requestBody
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Response"

  /tweets/{tweetId}:
    get:
      summary: Get tweet
      description: Return tweet
      parameters:
        - name: tweetId
          in: path
          description: Tweet ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tweet"
        "400":
          description: Invalid parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid parameter
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error404Response"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Response"
    put:
      summary: Update tweet
      description: Return updated time
      parameters:
        - name: tweetId
          in: path
          description: Tweet ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Hello World
                body:
                  type: string
                  example: Hello World
              required:
                - title
                - body
      responses:
        "204":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  updated_at:
                    type: string
                    format: date-time
                    example: 2021-01-01T00:00:00Z
        "400":
          description: Invalid parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid parameter
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
  /user:
    get:
      summary: Get user
      description: Return user
      tags:
        - Auth
      parameters:
        - in: cookie
          name: jwt
          schema:
            type: string
          required: true
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  username:
                    type: string
                    example: Alice
                  display_name:
                    type: string
                    example: alice
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
  /signin:
    post:
      summary: Sign in
      description: Sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: Alice
                password:
                  type: string
                  example: password
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/User"
        "400":
          description: Invalid parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /comments:
    get:
      summary: Get comments
      description: Return comments
      parameters:
        - name: limit
          in: query
          description: Limit
          required: false
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          description: Offset
          required: false
          schema:
            type: integer
            default: 0
        - name: post_id
          in: query
          description: Post ID
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          description: Sort
          required: false
          schema:
            type: string
            enum:
              - created_at
              - created_at:
                  - asc
                  - desc
            default: created_at:desc
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comments"
        "400":
          description: Invalid parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid parameter
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error404Response"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Response"
    post:
      summary: Create a new comment
      description: Create a new comment for a post.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: "Reference to User ID"
                  example: 1
                title:
                  type: string
                  example: Hello World
                body:
                  type: string
                  example: Hello World
              required:
                - user_id
                - title
                - body
      responses:
        "201":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  created_at:
                    type: string
                    format: date-time
                    example: 2021-01-01T00:00:00Z
        "400":
          description: Invalid parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid parameter
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Response"

  /comments/{commentId}:
    put:
      summary: Update a comment
      description: Update a specific comment by ID.
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  example: Hello World
              required:
                - body
      responses:
        "204":
          description: Updated comment entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  updated_at:
                    type: string
                    format: date-time
                    example: "2021-01-01T00:00:00Z"
        "400":
          description: Comment not found or not owned by the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Comment not found or not owned by the user
    delete:
      summary: Delete a comment
      description: Delete a specific comment by ID.
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A successful response
        "400":
          description: Comment not found or not owned by the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Comment not found or not owned by the user
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error404Response"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500Response"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        username:
          type: string
          example: Alice
        display_name:
          type: string
          example: alice
      required:
        - id
        - username
        - display_name
    Tweet:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        user_id:
          type: integer
          description: "Reference to User ID"
          example: 1
        title:
          type: string
          example: Hello World
        body:
          type: string
          example: Hello World
        created_at:
          type: string
          format: date-time
          example: 2021-01-01T00:00:00Z
          readOnly: true
        updated_at:
          type: string
          format: date-time
          example: 2021-01-01T00:00:00Z
          readOnly: true
        deleted_at:
          type: string
          format: date-time
          example: 2021-01-01T00:00:00Z
          readOnly: true
      required:
        - id
        - user_id
        - title
        - body
        - created_at
        - updated_at
    TweetsList:
      type: array
      items:
        type: object
        properties:
          tweet:
            $ref: "#/components/schemas/Tweet"
    Comment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        post_id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        body:
          type: string
          example: 新しいプロジェクトを始めるのが楽しみです！
        created_at:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
    Comments:
      type: array
      items:
        $ref: "#/components/schemas/Comment"
    Error404Response:
      type: object
      properties:
        message:
          type: string
          example: Not found
    Error500Response:
      type: object
      properties:
        message:
          type: string
          example: Internal server error
